"""links table

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-12 02:39:34.074716

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "links",
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("source_note_id", sa.UUID(), nullable=False),
        sa.Column("target_note_id", sa.UUID(), nullable=True),
        sa.Column("target_title", sa.String(length=1024), nullable=False),
        sa.Column("is_embed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["source_note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_note_id"], ["notes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_note_id", "target_title", "is_embed", name="uq_links_source_target"),
    )
    op.create_index("ix_links_vault_source", "links", ["vault_id", "source_note_id"], unique=False)
    op.create_index("ix_links_vault_target_note", "links", ["vault_id", "target_note_id"], unique=False)
    op.create_index("ix_links_vault_target_title", "links", ["vault_id", "target_title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_links_vault_target_title", table_name="links")
    op.drop_index("ix_links_vault_target_note", table_name="links")
    op.drop_index("ix_links_vault_source", table_name="links")
    op.drop_table("links")
    # ### end Alembic commands ###
