"""search and tags

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-12 02:45:01.071181

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pg_trgm powers the fuzzy quick-switcher title index below
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("vault_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["vault_id"], ["vaults.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vault_id", "name", name="uq_tags_vault_name"),
    )
    op.create_table(
        "note_tags",
        sa.Column("note_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("note_id", "tag_id"),
    )
    op.create_index("ix_note_tags_tag", "note_tags", ["tag_id"], unique=False)
    op.add_column(
        "notes",
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(title, '')), 'A') || setweight(to_tsvector('english', coalesce(content, '')), 'B')",
                persisted=True,
            ),
            nullable=True,
        ),
    )
    op.create_index("ix_notes_content_tsv", "notes", ["content_tsv"], unique=False, postgresql_using="gin")
    op.create_index(
        "ix_notes_title_trgm",
        "notes",
        ["title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_notes_title_trgm", table_name="notes", postgresql_using="gin", postgresql_ops={"title": "gin_trgm_ops"}
    )
    op.drop_index("ix_notes_content_tsv", table_name="notes", postgresql_using="gin")
    op.drop_column("notes", "content_tsv")
    op.drop_index("ix_note_tags_tag", table_name="note_tags")
    op.drop_table("note_tags")
    op.drop_table("tags")
    # ### end Alembic commands ###
